### ISSUE TITLE
Euclidean distance should be squared?

### ISSUE THREAD

**Issue by ya103** [hoxo-m/densratio#6]
https://github.com/hoxo-m/densratio/blob/3b877d5fdaf1b020a75c373b153b84210820934e/R/compute_kernel_Gaussian.R#L10

This line probably computes the Gaussian kernel.
If so, I think the Euclidean distance should be squared.

**Comment by hoxo-m** [comment]
Yes, you are right. 
You have found a big mistake that affects all the algorithms in this package.
Thank you for your big contribution.

**Comment by hoxo-m** [comment]
Fixed in release 0.1.0
https://github.com/hoxo-m/densratio/releases/tag/v0.1.0

**Comment by hoxo-m** [comment]
It is now on CRAN.
https://cran.r-project.org/package=densratio
